org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Mod info
mod_id=collectorsreap
mod_name=Collector's Reap
mod_version=1.0.0
mod_license=MIT License
mod_author=reNIK03, brdbrn
mod_description=Farmer's Delight addon with foods scavenged from the wild.
mod_issue_tracker=https://github.com/brnbrd/CollectorsReap/issues

# Minecraft / NeoForge
mc_version=1.21.1
neo_version=21.1.248
minecraft_version_range=[1.21.1]
neo_version_range=[21.1,)
loader_version_range=[1,)

# Parchment mappings
parchment_minecraft_version=1.21.1
parchment_version=2024.11.17

# Dependencies (Maven/CurseForge)
blueprint_version=1.21.1-8.1.2-beta
boatload_version=1.21.1-6.0.2
jei_file_id=8622758
farmers_delight_file_id=8672744
jade_file_id=8591319
brewin_and_chewin_file_id=8309583
neapolitan_file_id=7119475
