modLoader="javafml"
loaderVersion="[1,)"
license="MIT License"
issueTrackerURL="https://github.com/brnbrd/CollectorsReap/issues"

[[mods]]
modId="collectorsreap"
version="${mod_version}"
displayName="Collector's Reap"
displayURL="https://www.curseforge.com/minecraft/mc-mods/collectors-reap"
logoFile="collectorsreap.png"
logoBlur=false
credits="reNIK03, brdbrn, vectorwing"
authors="reNIK03, brdbrn"
description="Farmer's Delight addon with foods scavenged from the wild."
itemIcon="collectorsreap:lime_slice"
configBackground="collectorsreap:textures/block/urchin_test_bricks.png"
[modproperties.collectorsreap]
	configuredBackground="collectorsreap:textures/block/urchin_test_bricks.png"

[[dependencies.collectorsreap]]
	modId="neoforge"
	mandatory=true
	versionRange="[21.1,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.collectorsreap]]
	modId="farmersdelight"
	mandatory=true
	versionRange="[1.3.3,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.collectorsreap]]
	modId="blueprint"
	mandatory=true
	versionRange="[8.1.1,)"
	ordering="AFTER"
	side="BOTH"
